name: Udemy
description: Get paid udemy courses for free using this app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  url_launcher: any
  flutter_spinkit: "^4.1.2"
  google_fonts: ^1.1.0
  share: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
